import os
import json
from typing import Dict, Any, Optional
from sqlalchemy.orm import Session
from agenttrace.models import Incident, Trace, RegressionFixture
from agenttrace.replay.mock_context import extract_mock_fixtures_from_trace
from agenttrace.db import crud

def create_fixture_from_incident(
    db: Session,
    incident_id: int,
    custom_name: Optional[str] = None,
    description: Optional[str] = None
) -> RegressionFixture:
    """
    Creates a persistent regression fixture from a confirmed incident.
    Extracts recorded tool mocks and initial inputs so the regression suite can run in CI.
    """
    incident = crud.get_incident(db, incident_id)
    if not incident:
        raise ValueError(f"Incident {incident_id} not found")
        
    trace = incident.trace
    name = custom_name or f"regression_inc_{incident.id}_{incident.agent_name}"
    desc = description or f"Regression test for {incident.failure_bucket.value}: {incident.explanation[:120]}"
    
    mock_fixtures = extract_mock_fixtures_from_trace(trace)
    
    # Define assertion expectation (e.g. should not fail, should avoid offending action)
    assertion = {
        "should_not_reach_error": True,
        "prevented_step": incident.divergence_step_name,
        "original_failure_bucket": incident.failure_bucket.value if hasattr(incident.failure_bucket, "value") else str(incident.failure_bucket)
    }
    
    fixture = crud.create_regression_fixture(
        db=db,
        incident_id=incident.id,
        name=name,
        agent_name=incident.agent_name,
        initial_inputs=trace.initial_inputs or {},
        mocked_tool_fixtures=mock_fixtures,
        expected_outcome_assertion=assertion,
        description=desc
    )
    return fixture

def export_pytest_file(fixture: RegressionFixture, output_dir: str = "tests/regressions") -> str:
    """
    Generates a standalone executable pytest test file for CI pipelines.
    """
    os.makedirs(output_dir, exist_ok=True)
    filename = f"test_regression_{fixture.id}.py"
    filepath = os.path.join(output_dir, filename)
    
    code = f'''"""
Auto-generated by AgentTrace on confirmed incident.
Fixture: {fixture.name}
Agent: {fixture.agent_name}
Description: {fixture.description}
"""
import pytest
from agenttrace.replay import ReplaySandbox, get_agent_runner

INITIAL_INPUTS = {json.dumps(fixture.initial_inputs, indent=4)}
MOCKED_FIXTURES = {json.dumps(fixture.mocked_tool_fixtures, indent=4)}
EXPECTED_ASSERTIONS = {json.dumps(fixture.expected_outcome_assertion, indent=4)}

def test_regression_{fixture.id}():
    runner = get_agent_runner("{fixture.agent_name}")
    if not runner:
        pytest.skip("Agent runner '{fixture.agent_name}' not registered in test environment")
        
    with ReplaySandbox(MOCKED_FIXTURES) as sandbox:
        output = runner(INITIAL_INPUTS)
        
        # Verify no error occurred
        if isinstance(output, dict):
            assert not output.get("error"), f"Agent regression failed with error: {{output.get('error')}}"
            assert output.get("status") not in ["failed", "failure", "error"], f"Agent status is {{output.get('status')}}"
'''
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(code)
        
    return filepath
